### ISSUE TITLE
Getting error while pushing: RPC failed; HTTP 408 curl 18 HTTP/2 stream 7 was reset send-pack: unexpected disconnect while reading sideband packet fatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by dharmenbavaria** [cpina/github-action-push-to-another-repository#103]
Suggestion: read carefully the GitHub Action output. It might contain information that might help fixing the problem. If not please keep opening the bug report.

The documentation might have information on what you could do to fix the problem.

**Copy-paste the output of the GitHub Action**

name: Pushes build another repository

Full output might contain useful information including the git command, git output and settings used. It also helps to search for the problem later on.

      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: *****
      with:
        source-directory: 'web-publish'
        destination-github-username: 'ABC'
        destination-repository-name: 'RELEASE-Repo'
        user-email: dbc@gmail.com
        target-branch: ${{ github.ref_name }}  

**URL to the execution**
Push fails with this action I have in my pipeline. It feels like it has to do something with the file size or something. Because if I revert the code this action passes but if I make any new changes in the code it fails with that error I mentioned in the title. 

I am pasting the error of that message clear over here also

[+] Pushing git commit
error: RPC failed; HTTP 408 curl 18 HTTP/2 stream 7 was reset
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly

**Comment by FreelancerMarketplaces** [comment]
We're also encountering this issue; may be related to a large file committed.

**Comment by cpina** [comment]
In the original message in this thread I see:
```
    API_TOKEN_GITHUB: *****
```
So you are using the Personal Access Token which uses the https:// git backend.

Given the error message (and past experience) and @FreelancerMarketplaces : I think that there is some big file involved in the problem.

Could you try using the ssh keys approach? https://cpina.github.io/push-to-another-repository-docs/setup-using-ssh-deploy-keys.html#setup-ssh-deploy-keys

In the past (a few months ago): when I saw this type of error it got solved (or worked-arounded) using the ssh keys (since then git uses the ssh backend with different timed outs/limits it seems).

**Comment by alexanderameye** [comment]
> In the original message in this thread I see:
> 
> ```
>     API_TOKEN_GITHUB: *****
> ```
> 
> So you are using the Personal Access Token which uses the https:// git backend.
> 
> Given the error message (and past experience) and @FreelancerMarketplaces : I think that there is some big file involved in the problem.
> 
> Could you try using the ssh keys approach? https://cpina.github.io/push-to-another-repository-docs/setup-using-ssh-deploy-keys.html#setup-ssh-deploy-keys
> 
> In the past (a few months ago): when I saw this type of error it got solved (or worked-arounded) using the ssh keys (since then git uses the ssh backend with different timed outs/limits it seems).

In my case there were no large files involved. The commit itself was really small.

There is also this discussion https://github.com/orgs/community/discussions/55820. I'll try using the SSH keys.

**Comment by cpina** [comment]
As soon as I can I'll do some tests as well. Thanks for the link to the related discussion.

**Comment by MarkParker5** [comment]
> I haven't been able to reproduce the problem on my side, but in https://github.com/orgs/community/discussions/55820 it says a possible solution.
> 
> If you have this problem try with the `@devel` branch using:
> 
> ```
> uses: cpina/github-action-push-to-another-repository@devel
> ```
> 
> And let me know if it's fixed there.

This fixed the issue for me! Thanks!

**Comment by alexanderameye** [comment]
> I haven't been able to reproduce the problem on my side, but in https://github.com/orgs/community/discussions/55820 it says a possible solution.
> 
> If you have this problem try with the `@devel` branch using:
> 
> ```
> uses: cpina/github-action-push-to-another-repository@devel
> ```
> 
> And let me know if it's fixed there.

Fixed for me as well! Thanks for the quick response and sharing this awesome action!

**Comment by cpina** [comment]
Now `main` branch and `v1.7.1` include the fix for the problem.

Thanks @alexanderameye and @MarkParker5 for your feedback about the fix (and all the rest for the comments that you had the problem!)

**Comment by cpina** [comment]
The work around seems to not be needed anymore and will be removed in a future version (for what was discussed in https://github.com/orgs/community/discussions/55820). At the moment, to avoid changes right now (and because it works as expected), I'm closing the ticket
