### ISSUE TITLE
How to push tags as well?

### ISSUE THREAD

**Issue by TomasVotruba** [cpina/github-action-push-to-another-repository#12]
Hi,

thank you for amazing package. It's doing so much work for me :+1: 

I have a use case, when I push `master` branch.
I also need to push current tag.

In Travis, it was possible to do something like this:

```yaml
 - if [ "${TRAVIS_TAG}" != "" ]; then git tag "${TRAVIS_TAG}" && git push --quiet origin ${TRAVIS_TAG}; fi
```

Would something like this be possible here too?

Thank you

**Comment by cpina** [comment]
Hi Tomas,

I'm happy that this Github Action is helping you.

I'm not sure if I fully understand what you want to do. But before changing the current code I've thought of something. I've added in a branch that the `github-action-push-to-another-repository` sets a variable named `DESTINATION_CLONED_DIRECTORY`:
https://github.com/cpina/github-action-push-to-another-repository/compare/output-checkout?expand=1

Then this can be accessed in the next step:
https://github.com/cpina/push-to-another-repository-example/blob/master/.github/workflows/ci.yml#L33

If I merged this branch: would then you be able to execute the git tag command?

I think that it might be useful for your use case and other users use cases without having to tweak the main script.

Thank you!

**Comment by TomasVotruba** [comment]
Hi Carles,

thanks for a quick reply. I see I could explain it better.

- we have a monorepo migrify/migrify: https://github.com/migrify/migrify
- it has the push action GitHub Workflow: https://github.com/migrify/migrify/blob/master/.github/workflows/monorepo_split_packages.yaml
- we have a tag 0.3.53: https://github.com/migrify/migrify/tags

Now we need to push `master` branch and the tag that was just pushed into it from local.

```bash
# from local machine; origin = the Github mono repository
git tag 0.3.54 && git push --tags
```

Now the migrify/migrify is tagged - https://github.com/migrify/migrify

The workflow split pushes the `master`  to https://github.com/migrify/config-transformer
That works. 

The missing part is pushing the tag too, so here should be 0.3.53 and 0.3.54: https://github.com/migrify/config-transformer/tags

**Comment by cpina** [comment]
Thanks - I'll look at this properly! (I don't have time right now but tomorrow or Saturday yes for sure :-) )

**Comment by TomasVotruba** [comment]
Thank you, no rush :)

**Comment by orihomie** [comment]
Hi there, waiting for tags too.

**Comment by TomasVotruba** [comment]
In the end, I've solved this with custom GitHub Action, that is tailed to monoreno needs:
https://github.com/symplify/monorepo-split-github-action/
