### ISSUE TITLE
How to make "no change to commit" fail?

### ISSUE THREAD

**Issue by TomasVotruba** [cpina/github-action-push-to-another-repository#13]
Hi,

in a case when there are no changes vs remove branch, the job will fail.

![image](https://user-images.githubusercontent.com/924196/98184149-fa556800-1f09-11eb-9225-b514ebc3dc55.png)

https://github.com/rectorphp/rector/runs/1355898228

How shall I avoid it?

Thank you

**Comment by cpina** [comment]
Hi Tomas,
Sorry about this error - it happened because of some other changes that I made yesterday (since this is used I might think of better tests for this tool)

I've done a quick fix that should fix this, I'll close this ticket but please re-open if you still have the issue.

**Comment by TomasVotruba** [comment]
Hi, no problems,

thanks for quick fix!

**Comment by TomasVotruba** [comment]
Btw, how can I updated to the latest version?

I use `@dev`, but the error is still there: https://github.com/symplify/symplify/runs/1359514607
(build finished 6 minutes ago)

**Comment by cpina** [comment]
@TomasVotruba : could you try again please? In my morning rush I pushed the commit that was supposed to fix it in the wrong branch. I've tested with a re-build-no changes and it worked fine here. If it doesn't work I'll carefully check the logs of your build.

**Comment by TomasVotruba** [comment]
Sure. I need to run now, but this was the failed build: https://github.com/symplify/symplify/runs/1359514607

I've just retriggered it...
