### ISSUE TITLE
Pushing commit fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by gabrielradureaupw** [cpina/github-action-push-to-another-repository#18]
Hello,
The github action is failing me at the last step. Cloning, and commiting worked fine but I get the following error at the last step.
![image](https://user-images.githubusercontent.com/74105788/104357875-082cf800-550e-11eb-9165-5debadd4ff16.png)
How can I help ?

**Comment by cpina** [comment]
Hi Gabriel,
In order to help easier: do you have a link to the GitHub Action that is failing? (if it's a public repo it's easy). I haven't had this problem or seen it.
Hopefully then I can help easier!

**Comment by gabrielradureaupw** [comment]
Thank you @cpina for your quick reply, the error was on my part. Sorry for the disturbance.

**Comment by arnavs** [comment]
I had the same bug just now. I think it's either a misconfigured API key or the old syntax doesn't work. This is the commit that fixed it:  https://github.com/QuantEcon/lecture-datascience.myst/commit/53f772a7dac6d18707751c9c9e3a68d250ec30be

Could easily be the API key, but wouldn't that generate its own error? (i.e., something like `can't authenticate`)

**Comment by ethangk** [comment]
Thanks for creating this action! I was running into this issue too. For anyone else that's experiencing this, my case was caused by not setting up the api token, as described [here](https://github.com/marketplace/actions/push-directory-to-another-repository#api_token_github-environment)
