### ISSUE TITLE
Feature Suggesion: Add a option use for switch  whether overwrite all clone file 

### ISSUE THREAD

**Issue by fanlushuai** [cpina/github-action-push-to-another-repository#19]
just like:

finnal-push ：[keep source | keep source and target but overwrite if name exsit |   keep source and target but keep others if name exist |]

**Comment by Gaming32** [comment]
Please add this option. Without this option, this action will be impossible for me to use.

**Comment by cpina** [comment]
I think that this could be implemented outside the action following a similar pattern to https://cpina.github.io/push-to-another-repository-docs/faq.html#how-can-i-copy-only-some-files-only-some-directories-exclude-some-files-etc using a step before the action

If this is still wanted I will take a look. If not I might close it for now.
