### ISSUE TITLE
Option for destination folder on target repository

### ISSUE THREAD

**Issue by donnisnoni** [cpina/github-action-push-to-another-repository#23]
Would be nice if this action provide an option to specify destination folder on target repository

**Comment by piranna** [comment]
It seems like https://github.com/DevOpenWRT-Router/github-action-push-to-another-repository implements this, can it be merged?

**Comment by softmarshmallow** [comment]
https://github.com/cpina/github-action-push-to-another-repository/pull/41

**Comment by cpina** [comment]
As said: available on `main`, next week I plan to release a new version with this included in `v1.4`.
