### ISSUE TITLE
Error: Unable to resolve action `cpina/github-action-push-to-another-repository@master`, unable to find version `master`

### ISSUE THREAD

**Issue by tomtom94** [cpina/github-action-push-to-another-repository#28]
```
Error: Unable to resolve action `cpina/github-action-push-to-another-repository@master`, unable to find version `master`
```

This message appears in my github actions, before everything was totally until now.

What have done bro ???

**Comment by cpina** [comment]
A few days ago I renamed the default branch from "main" to "master" to follow GitHub new defaults. I had assumed (wrongly) that GitHub redirected the branches.

For now I've made the repository available on `main` (new default) and `master` so it should work for you again without changing anything.

Let me know if you have any related problems re-opening this issue. Thank you for the report and apologies for the problem.
