### ISSUE TITLE
Receive error when pushing to enterprise repo

### ISSUE THREAD

**Issue by dmnemec** [cpina/github-action-push-to-another-repository#3]
Tested the action against one of my own repos (dmnemec) and it worked fine. Switched the destination repo to the actual target (an enterprise repo) and it received the following error

```
error: src refspec master does not match any
error: failed to push some refs to 'https://***@github.com/enterprise/repo.git'
```

I haven't dug through the code, but could this be related to the token being generated from my account but the account name  and email in the action no longer being mine, but the enterprise account name instead? If so, would this require a PR to split those vars up (optionally)?

**Comment by dmnemec** [comment]
https://github.com/cpina/github-action-push-to-another-repository/pull/4

**Comment by cpina** [comment]
@dmnemec : can we close this ticket I guess after we merged your PR? thanks
