### ISSUE TITLE
Add an argument for folders / files to ignore

### ISSUE THREAD

**Issue by KaviiSuri** [cpina/github-action-push-to-another-repository#30]
A functionality to ignore some folders and files might be really useful.
I recently tried using this action to copy the whole repo to another repo in order to host it. 

`.git` folder was also copied in the copy step resulting in the action trying to push back to source repo and fails.

**Comment by cpina** [comment]
Thanks - this make sense.

Meanwhile some other users mentioned another solution: https://github.com/cpina/github-action-push-to-another-repository/issues/33

**Comment by harrietrs** [comment]
This would be a really useful addition- especially as currently using ./ as the source folder means that your git hooks are also included, which could create problems

**Comment by vencho-mdp** [comment]
Hi! Is there any way in which we could help with this? @cpina

**Comment by cpina** [comment]
@vencho-mdp : I would still like to prepare some tests to make sure that new options don't break existing options. Testing the combinations is hard. Perhaps some approaches could be discussed in https://github.com/cpina/github-action-push-to-another-repository/issues/59 ?

**Comment by cpina** [comment]
See (new) FAQ: https://cpina.github.io/push-to-another-repository-docs/faq.html#how-can-i-copy-only-some-files-only-some-directories-exclude-some-files-etc

Next days I plan to improve the FAQ but it links to an example of filtering that hopefully helps you.
