### ISSUE TITLE
Option to use ssh

### ISSUE THREAD

**Issue by sanihaq** [cpina/github-action-push-to-another-repository#32]

**Comment by cpina** [comment]
Thanks for the request - I wonder: is it not possible to use `https` with the `$API_TOKEN_GITHUB` for you?

**Comment by sanihaq** [comment]
Hi. sorry I should have explained it more at the time. I believe I was trying to do something with a private repository and https was not working. Again sorry. At the end I scrapped that project (not because of this).

**Comment by cpina** [comment]
Hi @sanihaq - no problem! Private repositories should work with the token, I'll close the ticket. If the action is pushing into a github repo the current way should work. ssh would help to push to non-github repos but the action would need to deal with ssh keys, etc.

Long story short: I'll close the issue for now :-) thanks anyway!
