### ISSUE TITLE
How to push the whole repository files to another repository ?

### ISSUE THREAD

**Issue by mehdi-developer** [cpina/github-action-push-to-another-repository#33]
How can I push the whole repository files to another repository ?
If I put an empty string it throws an error :
`
 - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ""
          destination-github-username: "username"
          destination-repository-name: "page"
          user-email: email@gmail.com
          commit-message: commit message
          target-branch: master
`

**Comment by Shahzad6077** [comment]
@mehdi-developer ? is that work for you?

**Comment by mehdi-developer** [comment]
@Shahzad6077 No I used andstor/copycat-action@v3 for pushing the whole repo files and not a folder  .

**Comment by cpina** [comment]
For the record: I suspect that `source-branch: .` might have worked. I might try some day.

I'm happy that you found a solution though! :)

**Comment by cpina** [comment]
Related: https://github.com/cpina/github-action-push-to-another-repository/issues/30
