### ISSUE TITLE
Support GHES

### ISSUE THREAD

**Issue by marikaner** [cpina/github-action-push-to-another-repository#37]
Hi, your action seems like it is doing exactly what I would need, but I can't use it because it won't work with GHES as `github.com` is the hardcoded server url. It would be great to consider this, similar to the [checkout action](https://github.com/actions/checkout/blob/afe4af09a72596f47d806ee5f8b2674ec07fdc73/src/url-helper.ts#L22).

**Comment by cpina** [comment]
@marikaner : this is implemented thanks to https://github.com/cpina/github-action-push-to-another-repository/commit/c3f0aa4db9e5f583937038696908d4403942d38c .

It's available on the `main` branch. I plan to release a new one next week (`v1.4`).

Use the parameter `github-server`. I haven't tested myself but let me know if you find any problems.
