### ISSUE TITLE
Support Git LFS

### ISSUE THREAD

**Issue by concertypin** [cpina/github-action-push-to-another-repository#40]
I tried to upload the files as my personal report, but I saw this error.
```
remote: error: File 빨려들어갈 거 같애(마인크래프트) [GQYfmvrdySc].mkv is 165.31 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
To https://github.com/rophin/DownloadResult.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to '***github.com/rophin/DownloadResult.git'
```
So I looked up the document to see if Git LFS was also possible to commit, but I couldn't find it. That's why I want you to support the Git LFS commit.

**Comment by hjupter** [comment]
Any news about this?

**Comment by cpina** [comment]
hi @hjupter , @concertypin : current `main` and version `v1.6` (pre-release) has git-lfs support. I'll close this issue but feel free to open one if you find problems. We've tested and it worked for us but I'm not a git-lfs expert.
