### ISSUE TITLE
Problems using across organizations repositories

### ISSUE THREAD

**Issue by michelmetran** [cpina/github-action-push-to-another-repository#47]
It serves very well what I need.
I ran several tests on my personal account, with success.

However, when trying to use Git Action on an organization account, I get an error.
```
[+] Pushing git commit
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/open-geodata/open-geodata.github.io.git/'
```

Already tried:

1. Add the personal token I created in [https://github.com/settings/tokens](https://github.com/settings/tokens) as the organization secret. Did not work.
2. Add in the personal token, in addition to the "repo", the "workflow". Also to no avail.

Interestingly, if I try to push my organization repository, from a command line, using https, login and api, the push works!!
... that is, there is no problem with the credentials!... but the Git Action still doesn't work!

```
git add .

git commit -m "Test"

git push https://michelmetran:ghp_VpuqwZzBeFP...@github.com/open-geodata/open-geodata.github.io.git
```

Is there any way around the problem?

**Comment by michelmetran** [comment]
Sorry! More study and found out!

I inserted the token as secret of the private repository and it worked.
I was trying with the token as the secret of the organization and I read that
_"Organization secrets can only be used by public repositories on your plan."_

Can close this issue!
I will not delete it, in case anyone has this doubt!

**Comment by cpina** [comment]
Thanks for adding the solution :-)
