### ISSUE TITLE
could I push to another branch other than master?

### ISSUE THREAD

**Issue by jasontsaitks** [cpina/github-action-push-to-another-repository#5]
could I push to another branch other than master?

**Comment by cpina** [comment]
Ha! I was thinking of this while reviewing https://github.com/cpina/github-action-push-to-another-repository/pull/4 :-) not possible right now because "master" is hardcoded twice: https://github.com/cpina/github-action-push-to-another-repository/blob/master/entrypoint.sh but it could come from two variables (FROM_BRANCH and TO_BRANCH? ORIGIN_BRANCH and DESTINATION_BRANCH)

I might do it during the weekend or if you want to do a PR I'll review it of course.

**Comment by jasontsaitks** [comment]
thank you for ur response.
I am new to github action...

my goal is:
In repoA,

1. checkout from repoB
2. do some work, generate some files
3. commit change
4. push to a new branch in repoB 
5. create pull request in repoB to master

can this be done?

It looks like it is possible to do 1-4?
while waiting for your support, could you please guide me if it is possible to do 5?

**Comment by cpina** [comment]
1-4 will be able to be done after I implement different branches (or feel free to submit a PR).

Number 5 is not in the scope of this GitHub Action but in your actions and a different step it should be possible to do it using the GitHub API: https://docs.github.com/en/rest/reference/pulls#create-a-pull-request . I haven't used this API so I don't know the details but I would look there.

I haven't used the GitHub API but it seems possible

**Comment by dmnemec** [comment]
@jasontsaitks  For step 5 there, you could have an action that triggers on a push/commit/something to a branch that isn't master in repoB. Step 4 will require a new optional (so it's backwards compatible) argument for the action similar to what I added to the entrypoint.sh script in #4 . You could just have it default to `master` unless it's set, then replace `master` in the few places it's at in that file. I thought about doing that when I wrote that fix, but it was out of the scope for what I needed to do.

**Comment by cpina** [comment]
Your PR got merged and the step 5 as said it would be a different action. I'll close this comment and thanks for the PR (in August, I just forgot to close the issue).
