### ISSUE TITLE
Folders not being copied from depth 2?

### ISSUE THREAD

**Issue by softmarshmallow** [cpina/github-action-push-to-another-repository#53]
Origin

- A/
  - a.txt
  - B
    - b.txt

Output (from dest repo)

- A/
  - a.txt

The sub directory not being pushed. Am I the only one having this issue?

**Comment by cpina** [comment]
This is strange. Do you have this in a public repo that I could see the output of the action to see if I could debug it? (the logs, the source and the destination?).

**Comment by softmarshmallow** [comment]
@cpina  Sorry. my mistake It was caused by .gitignore's content. 
Hard to catch ;)

**Comment by cpina** [comment]
Thanks for the update :-)
