### ISSUE TITLE
Arg target-directory is not working

### ISSUE THREAD

**Issue by rafaeltovargarrido** [cpina/github-action-push-to-another-repository#54]
Hello I try to use this action but I think there a issue when I try to use the arg target-directory, can you help to undestand why I having this issue.

My pipeline is:

`name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        chmod +x ./build.sh
        ./build.sh
    - name: Push directory to another repository
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'output'
        destination-github-username: 'rafaeltovargarrido'
        destination-repository-name: 'restaurant'
        user-email: rafaeltovar1992@gmail.com
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
        target-branch: master
        target-directory: tr-rafa/hola`

I want to create this folder  **tr-rafa/hola** in the other repo with context of the folder output. 

Error I have when I run the action.

`copy-file
Unexpected input(s) 'target-directory', valid inputs are ['entryPoint', 'args', 'source-directory', 'destination-github-username', 'destination-repository-name', 'user-email', 'destination-repository-username', 'target-branch', 'commit-message']`

**Comment by laurentleseigneur** [comment]
Hi, I have the same issue using v1.3

even if arg is passed to the docker container

```
echo "[+] Action start"
SOURCE_BEFORE_DIRECTORY="$1"
SOURCE_DIRECTORY="$2"
DESTINATION_GITHUB_USERNAME="$3"
DESTINATION_REPOSITORY_NAME="$4"
GITHUB_SERVER="$5"
USER_EMAIL="$6"
USER_NAME="$7"
DESTINATION_REPOSITORY_USERNAME="$8"
TARGET_BRANCH="$9"
COMMIT_MESSAGE="${10}"
TARGET_DIRECTORY="${11}"
```

is this due to the `${11}` that could be `$11` ?

I Also notice that expected input does not match arg seen in the `action.yml` file

**Comment by cpina** [comment]
I'll try to have a look this evening. Sorry for the problems, I haven't had much time recently :-(

If you can post a link to your repo with config it might help when I have a look (not really needed but just in case I see something specific to you).

**Comment by laurentleseigneur** [comment]
Hi Carles,

Thanks for your quick response! 

my repo is private, but here is the action I use:

```
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_CROWNDIN }}
        with:
          source-directory: 'target/localization/app-ticketing'
          destination-github-username: 'bonitasoft-presales'
          destination-repository-name: 'presales-localization'
          user-email: actions@github.com
          target-branch: app-ticketing
          target-directory: app-ticketing

```

and the output:

```
Warning: Unexpected input(s) 'target-directory', valid inputs are ['entryPoint', 'args', 'source-directory', 'destination-github-username', 'destination-repository-name', 'user-email', 'destination-repository-username', 'target-branch', 'commit-message']
Run cpina/github-action-push-to-another-repository@v1.3
  with:
    source-directory: target/localization/app-ticketing
    destination-github-username: bonitasoft-presales
    destination-repository-name: presales-localization
    user-email: actions@github.com
    target-branch: app-ticketing
    target-directory: app-ticketing
    commit-message: Update from ORIGIN_COMMIT
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.13-8/x64
    API_TOKEN_GITHUB: ***
/usr/bin/docker run --name a7ca921242b39f457db5df351f5deb6b54_460cc2 --label 9916a7 --workdir /github/workspace --rm -e JAVA_HOME -e API_TOKEN_GITHUB -e INPUT_SOURCE-DIRECTORY -e INPUT_DESTINATION-GITHUB-USERNAME -e INPUT_DESTINATION-REPOSITORY-NAME -e INPUT_USER-EMAIL -e INPUT_TARGET-BRANCH -e INPUT_TARGET-DIRECTORY -e INPUT_DESTINATION-REPOSITORY-USERNAME -e INPUT_COMMIT-MESSAGE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/app-Ticketing/app-Ticketing":"/github/workspace" 9916a7:ca921242b39f457db5df351f5deb6b54  "target/localization/app-ticketing" "bonitasoft-presales" "presales-localization" "actions@github.com" "" "app-ticketing" "Update from ORIGIN_COMMIT"


```

**Comment by laurentleseigneur** [comment]
seems this option is available on main branch, but not on v1.3 tag. I will give a try using "main" instead of tag

**Comment by laurentleseigneur** [comment]
problem is solved if I use
`uses: cpina/github-action-push-to-another-repository@main` instead of `v1.3`, even if I would prefer to use a tag, this works for me

Thanks again for this useful action

**Comment by cpina** [comment]
Excellent! Thanks for letting me and everyone know. I need to release `main` to `v1.4` to avoid these problems.

**Comment by cpina** [comment]
Closing as I published a new version that would have worked for you @laurentleseigneur (based on main)

Times flies, almost 8 months without publishing - apologies, busy year!

Thanks all,

**Comment by laurentleseigneur** [comment]
👍 
thanks for the new release!
