### ISSUE TITLE
Unexpected target directory created called `1` 

### ISSUE THREAD

**Issue by Shahzad6077** [cpina/github-action-push-to-another-repository#55]
Hey @cpina, the release is not working as expected.

Here It's created a target directory called `1` I tried to pass the input `target-directory: './'` but got the same issue

![image](https://user-images.githubusercontent.com/44517352/150528701-1d0ea253-13b9-4563-be8b-549fdadb3304.png)

**Comment by cpina** [comment]
Thanks @Shahzad6077 - I'll look into this and update the ticket.

To make sure that I fix what you've found: do you have a link to the repo that you've tried using the target-directory?
(I'm going to try it anyway but just in case it helps)

Thanks!

**Comment by Shahzad6077** [comment]
I've used the action in the private repo, I will reproduce it in the public repo and share the link.

**Comment by cpina** [comment]
Don't worry, I can reproduce it. Fixing...

**Comment by cpina** [comment]
@Shahzad6077 : I've released v1.4.1 that should fix this (it did for me).

Many apologies. I want to sit down and write unit tests for the action and I haven't had time for this, sadly. It's in my to do list.

I'll close this ticket now but feel free to open it again if you find a problem. Very appreciated that the github action is used.

**Comment by adibozzhanov** [comment]
Was the issue fixed?

**Comment by Shahzad6077** [comment]
Awesome, Thanks
