### ISSUE TITLE
Push fails with unsafe repository fatal error

### ISSUE THREAD

**Issue by jcoryalvernaz** [cpina/github-action-push-to-another-repository#67]
Our actions started failing recently with the following error:

```
fatal: unsafe repository ('/tmp/tmp.ekmOIH' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /tmp/tmp.ekmOIH
```

[This](https://github.com/actions/checkout/issues/760) is a related issue that I found with the `checkout` action. It appears some have worked around this issue by adding a step before the action:

```
- name: work around permission issue
   run: git config --global --add safe.directory /tmp/tmp.ekmOIH
```

However, with this action, it looks like the `tmp` that gets created has a different id each time the action is run. So, I'm not sure how we could work around the issue. Any help or guidance on this would be great. Thanks!

**Comment by jcoryalvernaz** [comment]
I see that it looks like this issue is being addressed in [this commit](https://github.com/cpina/github-action-push-to-another-repository/commit/e28934e9fdf3115e5efe4be89e77535042260518). I was wondering when this might make it into a new version? Thanks so much for this awesome action!

**Comment by cpina** [comment]
I'll release a new version tonight or tomorrow the latest. Thanks for pinging!

**Comment by cpina** [comment]
v1.4.2 has the fix. It was already released but only as a pre-release, now is a final release. Cheers @jcoryalvernaz
