### ISSUE TITLE
How i send all of my repository to another? 

### ISSUE THREAD

**Issue by Poowerllz** [cpina/github-action-push-to-another-repository#76]
I need to push all my X repository to Y repository
In the example build.sh specifies only a few files.

**Comment by cpina** [comment]
You should be able to push all your X repository into Y repository. One way is to use as a `source-directory` the current directory (`.`) but then the `.github` folder is copied over and will trigger GitHub action on the destination repository. To avoid this (which confuses matters) I recommend to disable the GitHub Actions on the destination repo (as explained here: https://github.com/cpina/github-action-push-to-another-repository/issues/71#issuecomment-1186004697)

If you can wait 24 hours I should have time to write documentation for FAQ tomorrow morning and this is one of the questions that I wanted to add in the FAQ. I'll try to explain it better in the documentation.

**Comment by cpina** [comment]
Finally I've published the new documentation and covered this case: https://cpina.github.io/push-to-another-repository-docs/faq.html#how-can-i-copy-the-whole-repository

Please get in touch if something is not clear.
